schema: https://opendataproducts.org/v4.1/schema/odps.yaml
version: 4.1
product:
  details:
    en:
      name: "{{name}}"
      productID: "{{productID}}"
      visibility: "{{enum: private | invitation | organisation | dataspace | public}}"
      status: "{{enum: announcement | draft | development | testing | acceptance | production | sunset | retired}}"
      type: "{{enum: raw data | derived data | dataset | reports | analytic view | 3D visualisation | algorithm | decision support | automated decision-making | data-enhanced product | data-driven service | data-enabled performance | bi-directional}}"
      description: "{{description}}"
      valueProposition: "{{valueProposition}}"
      productVersion: "{{string: semver}}"
      portfolioPriority: "{{enum: critical | high | medium | low}}"
      governanceProfile: "{{enum: structured | enforced | automated | audit_ready}}"
      categories:
        - "{{category}}"
      tags:
        - "{{tag}}"

  dataHolder:
    en:
      legalName: "{{legalName}}"
      businessDomain: "{{businessDomain}}"
      contactName: "{{contactName}}"
      email: "{{email}}"
      URL: "{{holderUrl}}"
